# PROFILE & MODULARITY
include="~~/profiles.conf"
input-default-bindings=yes

# VIDEO OUTPUT & QUALITY
vo=gpu-next
gpu-api=vulkan
gpu-context=winvk
vulkan-async-transfer=yes
vulkan-queue-count=4
vulkan-swap-mode=fifo
vd-lavc-dr=yes

# COLOR MANAGEMENT
icc-profile-auto=yes

# HARDWARE DECODING
hwdec=vulkan
hwdec-codecs=all
hwdec-extra-frames=12

# HDR & TONE MAPPING
hdr-peak-percentile=99.95
hdr-compute-peak=yes
hdr-contrast-recovery=0.80
tone-mapping=bt.2390
tone-mapping-param=1.45
target-colorspace-hint=yes

# SCALING & RESAMPLING
scale=ewa_lanczossharp
dscale=lanczos
cscale=catmull_rom
correct-downscaling=yes
linear-downscaling=yes

# SHADER
glsl-shader="~~/shaders/FSRCNNX/FSRCNNX_x2_16-0-4-1_enhanced.glsl"
glsl-shader="~~/shaders/SSim/SSimSuperRes.glsl"
glsl-shader="~~/shaders/Depth_reality_boost/depth_reality_boost.glsl"
glsl-shader="~~/shaders/Glimmer_sharpen/glimmer-sharpen_0.40.glsl"

# INTERPOLATION & FRAME SYNC
interpolation=yes
initial-audio-sync=yes
framedrop=vo
tscale=oversample
tscale-window=sphinx
tscale-blur=0.6991556596428412
tscale-clamp=0.0
video-sync-max-video-change=5

# DITHERING
dither=fruit
dither-depth=10
dither-size-fruit=6
temporal-dither=yes
temporal-dither-period=4

# DEBANDING
deband-iterations=5
deband-threshold=128
deband-range=12
deband-grain=3

# AUDIO
ao=wasapi
audio-exclusive=no
audio-device=auto
audio-channels=auto
volume=50
volume-max=130
gapless-audio=yes
audio-pitch-correction=yes
audio-file-auto=fuzzy
audio-buffer=0.2

# YTDL FORMAT FILTER
ytdl-format=best

# SEEKING
hr-seek=yes
hr-seek-framedrop=no

# PLAYBACK BEHAVIOR
keep-open=yes
keep-open-pause=no
idle=yes
force-seekable=yes
save-position-on-quit=yes
directory-mode=ignore

# WINDOW & UI
osc=no
border=no
autofit=70%x70%
geometry=50%:50%
snap-window=yes
cursor-autohide=800

# SUBTITLES
sub-font="Segoe UI Light"
sub-font-size=60
sub-color="#ffff00"
sub-border-size=1.2
sub-outline-color="#ff0000"
sub-shadow-color="#000000"
sub-shadow-offset=0.7
sub-blur=0.0
sub-back-color="#00000000"
sub-auto=no
sub-ass-override=no
sub-fix-timing=yes
blend-subtitles=yes
demuxer-mkv-subtitle-preroll=yes
sub-file-paths=sub,subs,subtitles
slang=en,eng,English
alang=en,eng,English
script-opts-append=trackselect-preferred_sub_lang=en/eng/english
script-opts-append=trackselect-excluded_sub_words=sign/s&s
script-opts-append=trackselect-preferred_audio_lang=en/eng/english

# OSD
osd-align-x=center
osd-font-size=28

# FILE PATHS & CACHE
demuxer-max-bytes=100MiB
demuxer-readahead-secs=10
cache=no

# LOGGING
msg-level=all=warn
