# PROFILE & MODULARITY
include="~~/profiles.conf"
input-default-bindings=yes

# VIDEO OUTPUT & QUALITY
vo=gpu-next
gpu-api=vulkan
gpu-context=winvk
vulkan-async-transfer=yes
vulkan-queue-count=4
vulkan-swap-mode=fifo
vd-lavc-dr=yes

# COLOR MANAGEMENT
icc-profile-auto=yes

# HARDWARE DECODING
hwdec=vulkan
hwdec-codecs=all
hwdec-extra-frames=12

# HDR & TONE MAPPING
hdr-peak-percentile=99.95
hdr-compute-peak=yes
hdr-contrast-recovery=0.80
tone-mapping=bt.2390
tone-mapping-param=1.45
target-colorspace-hint=yes
target-prim=bt.2020

# SCALING & RESAMPLING
scale=ewa_lanczossharp
scale-antiring=0.001
dscale=lanczos
cscale=catmull_rom
correct-downscaling=yes
linear-downscaling=yes

# SHADER
glsl-shader="~~/shaders/FSRCNNX/FSRCNNX_x2_16-0-4-1_enhanced.glsl"
glsl-shader="~~/shaders/SSim/SSimSuperRes.glsl"
glsl-shader="~~/shaders/Adaptive_sharpen/adaptive-sharpen-0.3.glsl"
glsl-shader="~~/shaders/Glimmer_sharpen/glimmer-sharpen_0.41.glsl"
glsl-shader="~~/shaders/FilmEmulation_Kodak/Kodak_2383_Procedural.glsl"
glsl-shader="~~/shaders/Depth_reality_boost/depth_reality_boost.glsl"
glsl-shader-opts=debug=no,fast=yes

# INTERPOLATION & FRAME SYNC
interpolation=yes
initial-audio-sync=yes
framedrop=vo
video-sync=audio
tscale=oversample
tscale-window=sphinx
tscale-blur=0.6991556596428412
tscale-clamp=0.0
tscale-radius=1.0
tscale-taper=0.0
tscale-antiring=0.05
video-sync-max-video-change=3

# DITHERING
dither=fruit
dither-depth=10
dither-size-fruit=6
temporal-dither=yes
temporal-dither-period=4

# DEBANDING
deband-iterations=4
deband-threshold=96
deband-range=10
deband-grain=3

# AUDIO
ao=wasapi
audio-exclusive=no
audio-device=auto
audio-channels=auto
volume=50
volume-max=130
gapless-audio=yes
audio-pitch-correction=yes
audio-file-auto=fuzzy
audio-buffer=0.2
audio-normalize-downmix=yes
audio-stream-silence=yes

# YTDL FORMAT FILTER
ytdl-format="bestvideo+bestaudio/best"

# SEEKING
hr-seek=yes
hr-seek-framedrop=no

# PLAYBACK BEHAVIOR
keep-open=yes
keep-open-pause=no
idle=yes
force-seekable=yes
save-position-on-quit=yes
directory-mode=ignore

# SCRIPTING & SESSION MANAGEMENT
load-scripts=yes
watch-later-directory=~~/watch_later

# WINDOW & UI
osc=no
border=no
autofit=70%x70%
geometry=50%:50%
snap-window=yes
cursor-autohide=800

# SUBTITLES
sub-font="Segoe UI Light"
sub-font-size=60
sub-color="#ffff00"
sub-border-size=1.2
sub-outline-color="#ff0000"
sub-shadow-color="#000000"
sub-shadow-offset=0.85
sub-blur=0.0
sub-back-color="#00000000"
sub-auto=fuzzy
sub-ass-override=no
sub-fix-timing=yes
blend-subtitles=yes
demuxer-mkv-subtitle-preroll=yes
sub-file-paths=sub,subs,subtitles
slang=en,eng,English
alang=en,eng,English
script-opts-append=trackselect-preferred_sub_lang=en/eng/english
script-opts-append=trackselect-excluded_sub_words=sign/s&s
script-opts-append=trackselect-preferred_audio_lang=en/eng/English
sub-clear-on-seek=yes
sub-delay=0

# OSD
osd-align-x=center
osd-font-size=28

# FILE PATHS & CACHE
demuxer-max-bytes=100MiB
demuxer-readahead-secs=10
cache=yes
cache-secs=20

# LOGGING
msg-level=all=warn
