# main_headset.conf
# Place in mpv/script-opts/ folder
# Used by main_headset.lua

sofa_path=sofa/hrtf_M_normal_pinna_resolution_0.5_deg.sofa
brir_path=sofa/ClubFritz12.sofa

sample_rate=48000
channel_layout_headset=stereo

headset_eq_profile=imax

loudnorm_headset=no
loudnorm_I=-23
loudnorm_TP=-2
loudnorm_LRA=7

normalize_fir=yes
dynamic_enabled=yes
