# main_cinema.conf
# Place in mpv/script-opts/ folder
# Used by main_cinema.lua

sofa_path=sofa/hrtf.sofa
ir_path=sofa/theatre_ir.wav

sample_rate=48000
channel_layout_speakers=5.1
channel_layout_headset=stereo

headset_eq_profile=imax
speaker_eq_profile=cinema

loudnorm_headset=false
loudnorm_speaker=true
loudnorm_I=-24
loudnorm_TP=-2
loudnorm_LRA=8

normalize_fir=true
dynamic_enabled=true