# Overlay timing
duration=4
redraw_delay=1
persistent_overlay=no

# Fonts and styling
font=Segoe UI
font_mono=Consolas
font_size=24
font_color=FFFFFF
border_size=1.0
border_color=262626
shadow_x_offset=0.5
shadow_y_offset=0.5
shadow_color=000000
alpha=40   # hex transparency (00=opaque, FF=fully transparent)

# Graphs
plot_perfdata=yes
plot_vsync_ratio=yes
plot_vsync_jitter=yes
skip_frames=5
global_max=yes
flush_graph_data=yes
plot_bg_color=262626
plot_bg_border_color=0000FF
plot_color=FFFFFF

# Filters
filter_params_max_length=100
