# uosc_screenshot.conf
# Customize screenshot behavior

# Save screenshots to this folder
screenshot_directory=~~/screenshots

# Screenshot format: png, jpg, or webp
screenshot_format=png

# Include subtitles in screenshots
include_subtitles=yes

# Show confirmation OSD
show_osd=yes
